TouristGuide/Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TouristGuide.Models
{
    public class Country
    {
        public int ID { get; set; }

        public string imgUrl { get; set; }

        [Required]
        public string Name { get; set; }

        public Coordinates Coordinates { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public string Description { get; set; }
    }
}

TouristGuide/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TouristGuide.Models;
using System.Text.RegularExpressions;
using System.IO;
using System.Data.Entity.Validation;
using System.Diagnostics;

namespace TouristGuide.Controllers
{ 
    public class CountryController : Controller
    {
        private TouristGuideDB db = new TouristGuideDB();

        //
        // GET: /Country/

        public ViewResult Index(int start = 0, int count = 20)
        {
            List<Country> countries = FilterCountries(null, start, count);
            return View(countries);
        }

        private List<Country> FilterCountries(string country, int start, int count)
        {
            IQueryable<Country> countries = db.Country;

            if (country != null && country != "")
            {
                countries = countries.Where(a => a.Name.Contains(country));
            }
            
            return countries.OrderBy(x => x.Name).Skip(start).Take(count).ToList();
        }

        public ViewResult GetCountries(string country, int start, int count)
        {
            List<Country> countries = FilterCountries(country, start, count);
            return View(countries);
        }

        //
        // GET: /Country/Details/5

        public ViewResult Details(int id)
        {
            Country country = db.Country.Include(c => c.Coordinates).Where(x => x.ID == id).Single();
            return View(country);
        }

        //
        // GET: /Country/Create
        [Authorize(Roles="admin")]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Country/Create
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(Country country)
        {
            if (ModelState.IsValid)
            {
                db.Country.Add(country);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = country.ID });
            }

            return View(country);
        }
        
        //
        // GET: /Country/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            Country country = db.Country.Find(id);
            return View(country);
        }

        //
        // POST: /Country/Edit/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = country.ID });
            }
            return View(country);
        }

        //
        // GET: /Country/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            Country country = db.Country.Find(id);
            return View(country);
        }

        //
        // POST: /Country/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Country country = db.Country.Find(id);
            db.Country.Remove(country);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AttractionsForCountry(string country)
        {
            //Get the data from the database
            var places = db.Place.Where(x => x.Country.Name == country).Include(c => c.Coordinates).Take(100);
            List<PushPinModel> pushpins = new List<PushPinModel>();

            //add info to list of pushpins
            foreach (var place in places)
            {
                //set the html to pass into the description
                string descriptionHtml;
                if (place.Description.Length > 200)
                {
                    descriptionHtml = Regex.Replace(place.Description, @"<.*?>", string.Empty);
                    descriptionHtml = descriptionHtml.Substring(0, 200) + "...";
                }
                else
                    descriptionHtml = place.Description;

                //add the pushpin info
                pushpins.Add(new PushPinModel
                {
                    Description = descriptionHtml,
                    Latitude = place.Coordinates.Latitude,
                    Longitude = place.Coordinates.Longitude,
                    Title = "<a href=\"/Place/Details/" + place.ID + "\">" + place.Name + "</a>"
                });
            }

            //return the list as JSON
            return Json(pushpins);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        [Authorize]
        public ActionResult removeImage(int CountryID)
        {

            
            string path = AppDomain.CurrentDomain.BaseDirectory;

            Country us = db.Country.Where(x => x.ID == CountryID).Single();
            System.IO.File.Delete(Path.Combine(path, us.imgUrl));
            
            us.imgUrl = "";
            db.Entry(us).State = System.Data.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Edit", new { id = us.ID });
        }
        [Authorize]
        [HttpPost]
        public ActionResult ImageCreate(int CountryID)
        {
            Country us = db.Country.Where(x => x.ID == CountryID).Single();
            if (us.imgUrl != null && us.imgUrl != "")
            {
                string path = AppDomain.CurrentDomain.BaseDirectory;
                System.IO.File.Delete(Path.Combine(path, us.imgUrl));
            }
            string FileName="";
            try
            {
                    string path = AppDomain.CurrentDomain.BaseDirectory + "Content/CountriesImages/";
                    string ext = Request.Files[0].FileName.Substring(Request.Files[0].FileName.LastIndexOf('.'));
                    FileName = generateRandomString(32) + ext;
                    System.Diagnostics.Debug.WriteLine(FileName);
                    Request.Files[0].SaveAs(Path.Combine(path, FileName));
                    FileName = Path.Combine("Content/CountriesImages/", FileName);
                    
                
            }
            catch (NullReferenceException)
            {
                //no photo
            }
            
            us.imgUrl = FileName;
            db.Entry(us).State = System.Data.EntityState.Modified;
            db.SaveChanges();


            return RedirectToAction("Edit", new { id = us.ID });
        }
      
        public String generateRandomString(int length)
        {
            //Initiate objects & vars    
            Random random = new Random();
            String randomString = "";
            int randNumber;

            //Loop ‘length’ times to generate a random number or character
            for (int i = 0; i < length; i++)
            {
                if (random.Next(1, 3) == 1)
                    randNumber = random.Next(97, 123); //char {a-z}
                else
                    randNumber = random.Next(48, 58); //int {0-9}

                //append random char or digit to random string
                randomString = randomString + (char)randNumber;
            }
            //return the random string
            return randomString;
        }
    }
}

TouristGuide/Views/Country/Create.cshtml
@model TouristGuide.Models.Country

@{
    ViewBag.Title = "Create country";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/tiny_mce/tiny_mce.js")" type="text/javascript"></script>
<script type="text/javascript">
    tinyMCE.init({
        mode: "specific_textareas",
        editor_selector: "TinyMCE",
        theme: "advanced"
    });

    function UpdateText() {
        var text = tinyMCE.get('Description').getContent();
        $('#Description').html(text);
    }
</script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Country</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { @class = "TinyMCE" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </fieldset>
    
    <fieldset>
        <legend>Location</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Coordinates.Latitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coordinates.Latitude)
            @Html.ValidationMessageFor(model => model.Coordinates.Latitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Coordinates.Longitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coordinates.Longitude)
            @Html.ValidationMessageFor(model => model.Coordinates.Longitude)
        </div>

        <p>
            <input type="submit" value="Create" onclick="UpdateText()" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TouristGuide/Views/Country/Delete.cshtml
@model TouristGuide.Models.Country

@{
    ViewBag.Title = Model.Name;
}

<h3>Are you sure you want to delete this country?</h3>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

<br />

<h4>Description:</h4>

<p>@Html.Raw(Model.Description)</p>

TouristGuide/Views/Country/Details.cshtml
@model TouristGuide.Models.Country

@{
    ViewBag.Title = Model.Name;
}

<script type="text/javascript" src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=6.2"></script>
<script type="text/javascript">
    $(document).ready(function () {
        GetMap();
        //call the action created to retrieve the data
        $.post("/Country/AttractionsForCountry?country=@Model.Name", null, function (data) {
            //iterate through the 'data' retireved
            $.each(data, function (item, location) {
                AddLocationPin(location.Latitude, location.Longitude, location.Title, location.Description);
            });
        });
    });
    var map = null;
    function GetMap() {
        map = new VEMap('myMap');
        map.LoadMap(new VELatLong(@Model.Coordinates.Latitude, @Model.Coordinates.Longitude), 5, 'Road', false);
    }
    function AddLocationPin(latitude, longitude, title, description) {      
        //create new pushpin shape      
        shape = new VEShape(VEShapeType.Pushpin, new VELatLong(latitude, longitude));      
        //set title for info box      
        shape.SetTitle(title);      
        //set html for info box      
        shape.SetDescription(description);      
        //add pin      
        map.AddShape(shape);  
    }

</script>

@if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

<div class="center">
    @Html.ActionLink("Cities/Regions","Index","Place", new {country = Model.Name},null) | 
    @Html.ActionLink("Attractions", "Index", "Attraction", new { country = Model.Name },null)
</div>
<br />
<div id='myMap' style="position: relative; width: 600px; height: 400px">
</div>
<p>@Html.Raw(Model.Description)</p>

TouristGuide/Views/Country/Edit.cshtml
@model TouristGuide.Models.Country

@{
    ViewBag.Title = Model.Name + " - Edit";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/tiny_mce/tiny_mce.js")" type="text/javascript"></script>
<script type="text/javascript">
    tinyMCE.init({
        mode: "specific_textareas",
        editor_selector: "TinyMCE",
        theme: "advanced"
    });

    function UpdateText() {
        var text = tinyMCE.get('Description').getContent();
        $('#Description').html(text);
    }
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Country</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { @class = "TinyMCE" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Save" onclick="UpdateText()" />
        </p>
    </fieldset>
}
@if (Model.imgUrl != null && Model.imgUrl!="")
{
	<h3 style="display: inline-block; margin-right:20px;">Images</h3>
    	
	<div class="post-images">
		<ul class="thumbs noscript">
	
				<li>
					<a class="thumb" href="@Url.Content("~/" + Model.imgUrl)" title="Image 1">
						<img src="@Url.Content("~/" + Model.imgUrl)" alt="Image 1" />
					</a>
				</li>
   
		</ul>
        @Html.ActionLink("Delete", "removeImage", new { CountryID = Model.ID })
	</div>
}

<div id="addImageDiv">
		@using (Html.BeginForm("ImageCreate", "Country", FormMethod.Post, new { enctype = "multipart/form-data", id =  "addImage",
                                onsubmit = "AddImage()"}))
  {
			@Html.ValidationSummary(true)
			<fieldset>
				<legend>Add Image</legend>
                @Html.Hidden("CountryID", Model.ID)  
				    <div class="editor-field-images">
                        <input type="file" name="FileName" id="FileName"/>
                    </div>
                    
                    <br />
                <input type="submit" value="Send!" />
			</fieldset>
  }
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TouristGuide/Views/Country/GetCountries.cshtml
@model IEnumerable<TouristGuide.Models.Country>
           
@{
    Layout = null;
}

@Html.DisplayFor(x=>x)

TouristGuide/Views/Country/Index.cshtml
@model IEnumerable<TouristGuide.Models.Country>

@{
    ViewBag.Title = "Countries";
}

<link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript">
    //pagger scrolling and filtering
    var more = true;
    var loading = false;
    var count = 20;
    var start = 0;
    var loaderImg = null;
    var country = '';

    $(document).ready(function () {
        country = $("#country").val();

        if ($('.countryBar').length < count) {
            more = false;
            HideLoading();
        }
        else {
            ShowLoading();
            $(window).scroll($.proxy(ScrollHandler, this));
        }

        AddActions();
    });

    function AddActions() {
        $(".countryBar").click(function () {
            var id = $(this).attr("name");
            var url = "/country/details/";
            window.location.replace(url + id);
        });

        $(".countryBar").hover(
          function () {
              $(this).css("background-image", "url(/Content/images/countryOrangeDark.png)");
          },
          function () {
              $(this).css("background-image", "url(/Content/images/countryOrange.png)");
          });
    }

    function ShowLoading() {
        loaderImg = $("<div>").addClass("bar").css("clear", "both").css("text-align", "center");
        var img = $("<img>").attr("src", "/Content/images/indicator.gif");
        loaderImg.append(img);
        $(".table_center").append(loaderImg);
    }

    function HideLoading() {
        $(loaderImg).remove();
    }

    function isScrolledIntoView(elem) {
        var docViewTop = $(window).scrollTop();
        var docViewBottom = docViewTop + $(window).height();

        var elemTop = $(elem).offset().top;
        var elemBottom = elemTop + $(elem).height();

        return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
    }

    function ScrollHandler(event) {
        if (isScrolledIntoView(loaderImg) && loading == false) {
            GetPage();
        }
    }

    function GetPage(event) {
        if (more == true) {
            start += count;
            GetElements();
            loading = true;
        }
    }

    function GetElements() {
        $.ajax({
            url: '@Url.Action("GetCountries", "Country")',
            type: 'GET',
            contentType: 'application/json',
            data: { country: country,
                start: start, count: count
            },
            dataType: 'html',
            success: $.proxy(Results, this)
        });
    }

    function Results(data) {
        if (data != null && data.trim() != '') {
            HideLoading();
            $(".table_center").append(data);
            if (data.split('<div class="countryBar"').length - 1 < count) {
                more = false;
                HideLoading();
            }
            else {
                ShowLoading();
                loading = false;
            }
            AddActions();
        }
        else {
            more = false;
            HideLoading();
        }
    }

    function Filter() {
        country = $("#country").val();

        $(".countryBar").remove();
        ShowLoading();

        more = true;
        loading = true;
        start = 0;
        GetElements();
    }

</script>
@Html.Partial("Partial/Autocomplete")

@if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<div class="center border-bottom search-cat">
<form action="/Country/Index" method="get">
<div style="font-size:20px;margin-bottom:20px;">Filter country </div>
   <span style="font-size:16px;padding-right:5px;">Country:</span> <input type="text" name="country" id="country" />
    <input type="submit" value="Filter" onclick="Filter(); return false;" style="margin-left:20px;color:Gray;"/>
</form>
</div>

<div  class="table_center">
<span style="font-size:20px;">Countries</span>

<div style="margin-top:20px;">
	@Html.DisplayFor(x=>x)
</div>
</div>