TouristGuide/Models/AttractionType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace TouristGuide.Models
{
    public class AttractionType
    {
        public int ID { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

TouristGuide/Models/AttractionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TouristGuide.Models
{
    public class AttractionViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

TouristGuide/Controllers/AttractionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TouristGuide.Models;
using System.Web.Security;
using TouristGuide.Helpers;
using System.IO;
using System.Data.Entity.Validation;
using System.Diagnostics;

namespace TouristGuide.Controllers
{
    public class AttractionController : Controller
    {
        private TouristGuideDB db = new TouristGuideDB();

        #region Attractions
        //
        // GET: /Attraction/

        public ViewResult Index(string country, string place, int start = 0, int count = 20)
        {
            List<Attraction> attractions = FilterAttractions(country, place, null, start, count, "rating", true);
            return View(attractions);
        }

        private List<Attraction> FilterAttractions(string country, string place, string attraction, int start,
            int count, string sort, bool desc)
        {
            IQueryable<Attraction> attractions = db.Attraction;

            if (country != null && country != "")
            {
                attractions = attractions.Where(a => a.Country != null && a.Country.Name.Contains(country));
            }
            if (place != null && place != "")
            {
                attractions = attractions.Where(a => (a.Address.City != null && a.Address.City.Contains(place))
                                                    || (a.Address.Region != null && a.Address.Region.Contains(place)));
            }
            if (attraction != null && attraction != "")
            {
                attractions = attractions.Where(x => x.Name != null && x.Name.Contains(attraction));
            }

            if (sort == "rating")
            {
                attractions = attractions.OrderByWithDirection(x => x.AvgRating, desc);
            }
            else if (sort == "leters")
            {
                attractions = attractions.OrderByWithDirection(x => x.Name, desc);
            }

            return attractions.Skip(start).Take(count).ToList();
        }

        public ViewResult GetAttractions(string country, string place, string attraction, int start, int count,
            string sort, bool desc)
        {
            List<Attraction> attractions = FilterAttractions(country, place, attraction, start, count, sort, desc);
            return View(attractions);
        }

        public ActionResult LookupCountry(String query, int limit = 50)
        {
            List<String> cats = db.Country.Where(x => x.Name.Contains(query)).Take(limit).Select(x => x.Name).ToList();
            var retValue = cats.Select(r => new { Country = r });
            return Json(retValue, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LookupPlace(String query, int limit = 50)
        {
            List<String> cats = db.Place.Where(x => x.Name.Contains(query)).Take(limit).Select(x => x.Name).ToList();
            var retValue = cats.Select(r => new { Place = r });
            return Json(retValue, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LookupAttraction(String query, int limit = 50)
        {
            List<String> cats = db.Attraction.Where(x => x.Name.Contains(query)).Take(limit).Select(x => x.Name).ToList();
            var retValue = cats.Select(r => new { Attraction = r });
            return Json(retValue, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Attraction/Details/5

        public ViewResult Details(int id)
        {
            var num = 10;
            //Attraction attraction = db.Attraction.Find(id);
            //attraction.Reviews = db.AttractionReview.Where(a => a.AttractionID == id).ToList();
            //attraction.Images = db.AttractionImage.Where(a => a.AttractionID == id).ToList();

            var attraction = db.Attraction.Include(a => a.Address).Include(c => c.Coordinates)
                .Include(c => c.Country).Include(c => c.AttractionType).Where(a => a.ID == id).SingleOrDefault();

            ViewData["Images"] = db.AttractionImage.Where(a => a.AttractionID == id && a.isApproved == 1).ToList();

            ViewData["Reviews"] = db.AttractionReview.Where(a => a.AttractionID == id && a.isApproved == 1).OrderByDescending(x => x.Date)
                .Take(num).ToList();
            return View(attraction);
        }

        public ViewResult GetReviews(int id, int start, int count)
        {
            var rev = db.AttractionReview.Where(a => a.AttractionID == id).OrderByDescending(x => x.Date)
                .Skip(start).Take(count).ToList();
            return View(rev);
        }

        //
        // GET: /Attraction/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.AttractionTypes = DbHelpers.GetAttractionTypesToList();
            ViewBag.Countries = DbHelpers.GetCountriesToList();
            return View();
        }

        //
        // POST: /Attraction/Create
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(Attraction attraction)
        {
            attraction.AttractionType = db.AttractionType.Find(attraction.AttractionType.ID);
            attraction.Country = db.Country.Find(attraction.Country.ID);
            attraction.AvgRating = 0.0;

            //upload photos
            try
            {
                int i = 0;
                foreach (string upload in Request.Files)
                {
                    if (Request.Files[i].ContentLength == 0)
                        continue;

                    string path = AppDomain.CurrentDomain.BaseDirectory + "Content/AttractionImages/";
                    string ext = Request.Files[i].FileName.Substring(Request.Files[i].FileName.LastIndexOf('.'));
                    AttractionImage ai = new AttractionImage { AttractionID = attraction.ID, FileName = generateRandomString(32) + ext };
                    attraction.Images.Add(ai);
                    Request.Files[i].SaveAs(Path.Combine(path, ai.FileName));
                    i++;
                }
            }
            catch (NullReferenceException)
            {
                //no photo
            }
            //end of upload user photo

            db.Attraction.Add(attraction);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = attraction.ID });
        }

        //
        // GET: /Attraction/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            ViewBag.AttractionTypes = DbHelpers.GetAttractionTypesToList();
            ViewBag.Countries = DbHelpers.GetCountriesToList();
            Attraction attraction = db.Attraction.Include(c => c.Country).Include(t => t.AttractionType).Include(c => c.Coordinates).Include(a => a.Address).Include(i => i.Images).Where(a => a.ID == id).SingleOrDefault();
            AttractionEditViewModel attractionEdit = new AttractionEditViewModel();
            attractionEdit.Attraction = attraction;
            return View(attractionEdit);
        }

        //
        // POST: /Attraction/Edit/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(AttractionEditViewModel attractionEdit)
        {
            var updatedAttraction = db.Attraction.Include(a => a.AttractionType).Include(c => c.Country).Include(c => c.Coordinates).Include(a => a.Address).Where(x => x.ID == attractionEdit.Attraction.ID).SingleOrDefault();
            updatedAttraction.AttractionType = db.AttractionType.Find(attractionEdit.Attraction.AttractionType.ID);
            updatedAttraction.Country = db.Country.Find(attractionEdit.Attraction.Country.ID);
            updatedAttraction.Coordinates.Latitude = attractionEdit.Attraction.Coordinates.Latitude;
            updatedAttraction.Coordinates.Longitude = attractionEdit.Attraction.Coordinates.Longitude;
            updatedAttraction.Address = attractionEdit.Attraction.Address;
            db.Entry(updatedAttraction).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { id = updatedAttraction.ID });
        }

        //
        // GET: /Attraction/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            Attraction attraction = db.Attraction.Find(id);
            return View(attraction);
        }

        //
        // POST: /Attraction/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Attraction attraction = db.Attraction.Find(id);
            //remove reviews
            var deleteAttractionReviews =
                    from attractions in db.AttractionReview
                    where attractions.AttractionID == id
                    select attractions;

            foreach (var review in deleteAttractionReviews)
            {
                db.AttractionReview.Remove(review);
            }
            //---

            //remove images
            var deleteAttractionImages =
                    from attractions in db.AttractionImage
                    where attractions.AttractionID == id
                    select attractions;
            try
            {
                string path = AppDomain.CurrentDomain.BaseDirectory + "Content/AttractionImages/";
                foreach (var img in deleteAttractionImages)
                {
                    FileInfo TheFile = new FileInfo(path + img.FileName);
                    if (TheFile.Exists)
                    {
                        TheFile.Delete();
                    }

TouristGuide/Views/Attraction/Create.cshtml
@model TouristGuide.Models.Attraction

@{
    ViewBag.Title = "Create";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/tiny_mce/tiny_mce.js")" type="text/javascript"></script>
<script type="text/javascript">
    tinyMCE.init({
        mode: "specific_textareas",
        editor_selector: "TinyMCE",
        theme: "advanced"
    });

    function UpdateText() {
        var text = tinyMCE.get('Description').getContent();
        $('#Description').html(text);
    }

    function addImgInput() {
        $('.editor-field-images').append("<input type='file' name='photo' />");
    }

    function delImgInput() {
        $('.editor-field-images input').last().remove();
    }
</script>
<script type="text/javascript">
    var map = null;

    function GetMap() {
        map = new VEMap('myMap');
        map.AttachEvent("ondoubleclick", AddPushpin);
        map.LoadMap();
        map.HideScalebar();
    }

    onload = GetMap;

    function AddPushpin(e) {
        map.Clear();
        var pixel = new VEPixel(e.mapX, e.mapY);
        var point = map.PixelToLatLong(pixel);

        var pin = new VEShape(VEShapeType.Pushpin, point);
        map.AddShape(pin);

        SetLatLong(point);

        return true;
    }

    function SetLatLong(point) {
        $('#Coordinates_Latitude').val(point.Latitude);
        $('#Coordinates_Longitude').val(point.Longitude);
    }
</script>

@using (Html.BeginForm("Create", "Attraction", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Details</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { @class = "TinyMCE" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </fieldset>
    
    <fieldset>
        <legend>Location</legend>

        <div style="display:inline-table">
        <div class="editor-label">
            @Html.LabelFor(model => model.Coordinates.Latitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coordinates.Latitude)
            @Html.ValidationMessageFor(model => model.Coordinates.Latitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Coordinates.Longitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coordinates.Longitude)
            @Html.ValidationMessageFor(model => model.Coordinates.Longitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Country)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Country.ID, new SelectList(ViewBag.Countries, "Value", "Text"))
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address.Region)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address.Region)
            @Html.ValidationMessageFor(model => model.Address.Region)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Address.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address.City)
            @Html.ValidationMessageFor(model => model.Address.City)
        </div>        

        <div class="editor-label">
            @Html.LabelFor(model => model.Address.Street)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address.Street)
            @Html.ValidationMessageFor(model => model.Address.Street)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address.BuildingNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address.BuildingNumber)
            @Html.ValidationMessageFor(model => model.Address.BuildingNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AttractionType)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.AttractionType.ID, new SelectList(ViewBag.AttractionTypes, "Value", "Text"))            
        </div>
        </div>
        <div style="display:inline-table; margin-left: 40px;">
            Double click on map to pick a location.
            <div id="myMap" style="position: relative; width: 300px; height: 300px;"></div>
        </div>

    </fieldset>
    
    <fieldset>
        <legend>Photos and Video</legend>
        
        <div class="editor-field-images">
            <input type="file" name="photo" />
        </div>
        <input type="button" value=" + " onclick="addImgInput()" /><input type="button" value=" - " onclick="delImgInput()" />

        <div class="editor-label">
            @Html.LabelFor(model => model.Video)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Video)
            @Html.ValidationMessageFor(model => model.Video)
        </div>
    </fieldset>

    <p>
        <input type="submit" value="Create" onclick="UpdateText()" />
    </p>
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TouristGuide/Views/Attraction/Details.cshtml
@model TouristGuide.Models.Attraction
@using TouristGuide.Models;

@{
	ViewBag.Title = Model.Name;
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#showreview").click(function () {
            $("#addreview").toggle();
        });
        $("#showImage").click(function () {
            $("#addImageDiv").toggle();
        });
        
        $(".fancybox").fancybox();
        

        GetMap();
    });

    function AddImage(){
        ResultImage();
        setTimeout("document.getElementById('addImage').submit()", 1000);
    }
    function ResultImage() {
            $("#addImageDiv").toggle();
            $('#showImage').after("<br/><p style='color:red'>Your image must be approved.</p>");
    }

    function AddReview() {
        AttractionId = $("#AttractionID").val();
        Author = $("#Author").val();
        Rating = $("#Rating").val();
        Text = $("#Text").val();

        $.ajax({
            url: '@Url.Action("ReviewCreate", "Attraction")',
            type: 'GET',
            contentType: 'application/json',
            data: { AttractionId: AttractionId, Author: Author,
                Rating: Rating, Text: Text
            },
            dataType: 'html',
            success: $.proxy(ResultReview, this)
        });
    }

    function ResultReview(data) {
        if (data != null && data.trim() != '') {
            $("#addreview").toggle();
            $('#showreview').after("<br/><p style='color:red'>Your review must be approved.</p>");
            $("#Text").val("");
            $("#Rating").val("");
        }
    }
</script>
<script type="text/javascript">
    var map = null;

    function GetMap() {
        map = new VEMap('myMap');

        var latitude = @Model.Coordinates.Latitude;
        var longitude = @Model.Coordinates.Longitude;
        
        map.LoadMap(new VELatLong(latitude, longitude),
                12, VEMapStyle.Road, false);
        map.HideScalebar();
        
        var shape = new VEShape(VEShapeType.Pushpin, new VELatLong(latitude, longitude)); 
        map.AddShape(shape);        
        
    }
</script>

@Html.Partial("Partial/ShowMore")

@Html.HiddenFor(x => x.ID)

@Html.ActionLink(Model.Country.Name, "Details", "Country", new { id = Model.Country.ID}, null)
@if(Model.Address.Region != null)
{
	<text>/</text>
	@Model.Address.Region;

}
@if (Model.Address.City != null)
{
	<text>/</text>
	@Model.Address.City;
}

<div class="post">
@if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("admin"))
{
		<p>
			@Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
			@Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
			@Html.ActionLink("Go back to attractions' index", "Index")
		</p>
}
 
 @Html.ActionLink("Add to favourites", "Add", "MyAttraction", new { attractionId = Model.ID }, null)

 <div id="myMap" style="position: relative; width: 600px; height: 300px;"></div>
	<p>@Html.Raw(Model.Description)</p>   
<div class="post-address">
<ul>
	<li><b>Avg. rating:</b> @String.Format("{0:0.00}", Model.AvgRating)</li>
	<li><b>Region:</b> @Model.Address.Region</li>
	<li><b>City:</b> @Model.Address.City</li>
	<li><b>Street:</b> @Model.Address.Street @Model.Address.BuildingNumber</li>
</ul>
</div>

<div id="addImageDiv" style="display: none">
		@using (Html.BeginForm("ImageCreate", "Attraction", FormMethod.Post, new { enctype = "multipart/form-data", id =  "addImage",
                                onsubmit = "AddImage()"}))
  {
			@Html.ValidationSummary(true)
			<fieldset>
				<legend>Add Image</legend>
                @Html.Hidden("Author", Context.User.Identity.Name)
				@Html.Hidden("AttractionID", Model.ID)  
				    <div class="editor-field-images">
                        <input type="file" name="FileName" id="FileName"/>
                    </div>
                    <div class="editor-label">
					    Title
				    </div>
                    <div class="editor-field-images">
                        <input type="text" id="Title" name="Title" />
                    </div>
                    <!--input type="button" value=" + " onclick="addImgInput()" /><input type="button" value=" - " onclick="    delImgInput()" /-->
                    <br />
                <input type="button" value="Send!" onclick="AddImage()"/>
			</fieldset>
  }
</div>
@if (Request.IsAuthenticated)
     {
		@:<a id="showImage" style="cursor: pointer;">Add Image</a><br />
	}
     else
     {
		@Html.ActionLink("Log on to add image", "LogOn", "Account", new { returnUrl = Request.RawUrl }, null)
        <br />
     }
				
@if (Model.Images.Count() > 0)
{
	<h3 style="display: inline-block; margin-right:20px;">Images</h3>
    <link rel="stylesheet" href="@Url.Content("~/Content/fancybox/jquery.fancybox-1.3.4.css")" type="text/css" media="screen" />
    <script type="text/javascript" src="@Url.Content("~/Content/fancybox/jquery.fancybox-1.3.4.pack.js")"></script>
	<div class="post-images">
		<ul class="thumbs noscript">
			@for (int i = 0; i < Model.Images.Count(); ++i)
   {   
				<li>
					<a class="fancybox" rel="group" href="@Url.Content("~/Content/AttractionImages/" + Model.Images[i].FileName)" title="@Model.Images[i].Title">
						<img src="@Url.Content("~/Content/AttractionImages/" + Model.Images[i].FileName)" alt="Image #@i" />
					</a>
                    <p>
                        <b>Title: </b>@Model.Images[i].Title
                    </p>
                    <p>
                        <b>Author: </b>@Model.Images[i].Author
                    </p>
                    <br />
				</li>
   }
		</ul>
	</div>

}
@if (Model.Video != null)
{
	<h3>Video</h3>
	<div class="post-video">
		<object style="height: 340px; width: 560px">
		<param name="movie" value="@Model.Video">
		<param name="allowFullScreen" value="true">
		<param name="allowScriptAccess" value="always">
		<embed src="@Model.Video" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="560" height="340">
		</object>
	</div>
}

<div id="addreview" style="display: none">
		@using (Html.BeginForm("ReviewCreate", "Attraction"))
  {
			@Html.ValidationSummary(true)
			<fieldset>
				<legend>Add review</legend>
				@Html.Hidden("Author", Context.User.Identity.Name)
				@Html.Hidden("AttractionID", Model.ID)
				<div class="editor-label">
					Rating (1-10)
				</div>
				<div class="editor-field">
					<input class="text-box single-line" data-val="true" data-val-range="Rating scale: 1-10" data-val-range-max="10" data-val-range-min="1" id="Rating" name="Rating" type="text" value="" />
				</div>

				<div class="editor-label">
					@Html.LabelFor(model => model.Description)
				</div>
				<div class="editor-field">
					<textarea rows="5" cols="10" class="text-box multi-line" data-val="true" data-val-required="The Text field is required." id="Text" name="Text"></textarea>
					<span class="field-validation-valid" data-valmsg-for="Text" data-valmsg-replace="true"/>
				</div>
				<p>
					<input type="submit" value="Send" onclick="AddReview(); return false;" />
				</p>
			</fieldset>
  }
</div>

	<h3 style="display: inline-block; margin-right: 20px;">Reviews</h3>

	@if (Request.IsAuthenticated)
 {
		@:<a id="showreview">Add review</a>
	}
 else
 {
		@Html.ActionLink("Log on to add review", "LogOn", "Account", new { returnUrl = Request.RawUrl }, null)
 }

	@if (Model.Reviews.Count == 0)
 {
		<div class="review">
			<p>No reviews.</p>
		</div>
 }    
    @foreach (var rev in ViewData["Reviews"] as List<AttractionReview>)
    { 
        @Html.DisplayFor(x => rev)
    }

</div>

TouristGuide/Views/Attraction/GetAttractions.cshtml
@model IEnumerable<TouristGuide.Models.Attraction>
           
@{
    Layout = null;
}

@Html.DisplayFor(m => m)

TouristGuide/Views/Attraction/GetImage.cshtml
@model TouristGuide.Models.AttractionImage
           
@{
    Layout = null;
}

@Html.DisplayFor(m => m)

TouristGuide/Views/Attraction/Index.cshtml
@model IEnumerable<TouristGuide.Models.Attraction>
@{
    ViewBag.Title = "Attractions";
}

<link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript">
    //pagger scrolling and filtering
    var more = true;
    var loading = false;
    var count = 20;
    var start = 0;
    var loaderImg = null;
    var country = '';
    var place = '';
    var attr = '';
    var sort = 'rating';
    var sortDesc = true;

    $(document).ready(function () {
        $("#country").val('@Request.QueryString["country"]');
        $("#place").val('@Request.QueryString["place"]');
        country = $("#country").val();
        place = $("#place").val();
        attr = $("#attraction").val();

        $("#sortByRating").click(function () {
            if (sort == 'rating') {
                sortDesc = sortDesc ? false : true;
            }
            else {
                $("#sortByRating").text('[avg rating]');
                $("#sortByLeters").text('alphbetically');
                sortDesc = true;
                sort = 'rating';
            }
            Sort();
        });

        $("#sortByLeters").click(function () {
            if (sort == 'leters') {
                sortDesc = sortDesc ? false : true;
            }
            else {
                $("#sortByRating").text('avg rating');
                $("#sortByLeters").text('[alphbetically]');
                sortDesc = false;
                sort = 'leters';
            }
            Sort();
        });

        if ($('.post').length < count) {
            more = false;
            HideLoading();
        }
        else {
            ShowLoading();
            $(window).scroll($.proxy(ScrollHandler, this));
        }
    });

    function ShowLoading() {
        loaderImg = $("<div>").addClass("bar").css("clear", "both").css("text-align", "center");
        var img = $("<img>").attr("src", "/Content/images/indicator.gif");
        loaderImg.append(img);
        $("#render").append(loaderImg);
    }

    function HideLoading() {
        $(loaderImg).remove();
    }

    function isScrolledIntoView(elem) {
        var docViewTop = $(window).scrollTop();
        var docViewBottom = docViewTop + $(window).height();

        var elemTop = $(elem).offset().top;
        var elemBottom = elemTop + $(elem).height();

        return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
    }

    function ScrollHandler(event) {
        if (isScrolledIntoView(loaderImg) && loading == false) {
            GetPage();
        }
    }

    function GetPage(event) {
        if (more == true) {
            start += count;
            GetAtt();
            loading = true;
        }
    }

    function GetAtt() {
        $.ajax({
            url: '@Url.Action("GetAttractions", "Attraction")',
            type: 'GET',
            contentType: 'application/json',
            data: { country: country, place: place,
                attraction: attr, start: start, count: count, sort: sort, desc: sortDesc
            },
            dataType: 'html',
            success: $.proxy(Results, this)
        });
    }

    function Results(data) {
        if (data != null && data.trim() != '') {
            HideLoading();
            $("#render").append(data);
            if (data.split('<div class="post attractionsLemonBg">').length - 1 < count) {
                more = false;
                HideLoading();
            }
            else {
                ShowLoading();
                loading = false;
            }
        }
        else {
            more = false;
            HideLoading();
            $("#noResults").attr("style", "");
        }
    }

    function Sort() {
        $(".post").remove();

        more = true;
        loading = true;
        start = 0;
        GetAtt();
    }

    function Filter() {
        country = $("#country").val();
        place = $("#place").val();
        attr = $("#attraction").val();
        $("#noResults").attr("style", "display:none;");

        $(".post").remove();

        more = true;
        loading = true;
        start = 0;
        GetAtt();
    }

</script>
@Html.Partial("Partial/Autocomplete")

<div class="left border-bottom search-cat">
    <p>
@if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("admin"))
{
    @Html.ActionLink("Add attraction", "Create")@: |
}
    Sort by: 
        <a id="sortByRating">[avg rating]</a> | <a id="sortByLeters">alphbetically</a>
    </p>
</div>

<div class="center border-bottom search-cat">
@using (Html.BeginForm())
{
    <div style="font-size:20px;margin-bottom:20px;">Filter Attractions</div>
   <span style="font-size:16px;padding-right:5px;padding-left:5px;">Country:</span>
    @Html.TextBox("country") 
	<span style="font-size:16px;padding-right:5px;padding-left:5px;">City/Region:</span>
    @Html.TextBox("place") 
   <span style="font-size:16px;padding-right:5px;padding-left:5px;">Attraction:</span>
   @Html.TextBox("attraction")
   <input type="submit" value="Filter" onclick="Filter(); return false;" style="margin:20px;color:Gray;"/>
}
</div>

@Html.DisplayFor(m => m)

<div id="noResults" class="attractionsLemonBg"
@if (Model == null || (Model != null && Model.Count() == 0))
{
    @:>
}
else
{ 
    @: style="display:none;">
}
    <h1 style="color:#9BB45E;" class="attractionTitleDarkLemonBg">No results found.</h1>
</div>