TouristGuide/Models/UserList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TouristGuide.Models
{
    public class UserList
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Write name")]
        [DataType(DataType.Text)]
        public String Name { get; set; }
    }
}

TouristGuide/Controllers/UserListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TouristGuide.Models;
using TouristGuide.Providers.Database;
using System.Data.Entity.Validation;
namespace TouristGuide.Controllers
{
    [Authorize]
    public class UserListsController : Controller
    {
        private TouristGuideDB db = new TouristGuideDB();
        private IDataProvider users = new SqlProvider();
        //
        // GET: /AttractionsLists/

        public ViewResult Index()
        {
            var id = users.GetUserByLogin(HttpContext.User.Identity.Name).UserId;
            var userList = db.UserLists.Where(x => x.UserId == id).Select(x => x).ToList();
            //var attractionsLists = db.AttractionsLists.Where(x => userList.Contains(x.ListId)).ToList();

            return View(userList);
        }
        public ActionResult Delete(int id)
        {
            UserList userList = db.UserLists.Where(x => x.ID == id).Single();

            var attractions = db.AttractionsLists.Where(x => x.ListId == userList.ID).ToList();

            foreach (AttractionsList item in attractions)
            {
                db.AttractionsLists.Remove(item);
            }

            db.UserLists.Remove(userList);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Show(int idd)
        {
            return RedirectToAction("Index", "AttractionsList", new { id = idd });
        }
        public ActionResult Create()
        {
            return View("Create");
        }
        public ActionResult AddList(UserList u)
        {
            var id = users.GetUserByLogin(HttpContext.User.Identity.Name).UserId;
            u.UserId = id;
            db.UserLists.Add(u);
            db.SaveChanges();
            
            return RedirectToAction("Index");
        }
        public String updateName(int id, String name)
        {
            UserList us = db.UserLists.Where(x => x.ID == id).Single();
            us.Name = name;
            db.Entry(us).State = System.Data.EntityState.Modified;
            db.SaveChanges();
            return "ok";
        }
    }
}

TouristGuide/Views/UserLists/Create.cshtml
@model TouristGuide.Models.UserList

@{
    
    ViewBag.Title = "New List";
  
}

@using (Html.BeginForm("AddList", "UserLists"))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>New List:</legend>
        @Html.LabelFor(model => model.Name)
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
        <input type="submit" value="Create" />
    </fieldset>
}
@Html.ActionLink(" ", "Index", "UserLists", null, new { @class = "imgBack", })

TouristGuide/Views/UserLists/Index.cshtml
@model IEnumerable<TouristGuide.Models.UserList>

@{
    
    
    ViewBag.Title = "User Attractions Lists";
}

<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    function hide() {
        $('#popup2').hide("slow");
        alert("AAA");
        return false;
    }
    ListID = -1;
    function showPopup(id, name)
    {
        $('#popup2').show("slow");
        ListID = id;
        $('#popuptext').val(name).focus();

        return false;
    }
    
    function hidePopup() {
        var text = $('#popuptext').val();
        $("#" + ListID).text(text);
        
        $.ajax({
            async: false,
            type: "POST",
            url: encodeURI('@Url.Action("updateName", "UserLists")'),
            data: { id: ListID, name: text }
        }).done(function (msg) {
            
        });
        $('#popup2').hide("slow");
        return false;
    }
    function cancel() {
        $('#popup2').hide("slow");
    }

</script>
<style type="text/css">

    #popup2
    {
        display: none;
        position: fixed;
        width: 150px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left:-150px;
        margin-top: -50px;
        border: 5px solid blue;
        background-color: #DEDFDE;
        padding: 30px;
        z-index: 102;
    }
    #content2
    {
        height: auto;
        width: auto;
        margin: auto;
        text-align: center;
    }
    .imgOk
    {
        display: inline-block;
        background: url('/Content/images/ok.png') no-repeat;
        width: 32px;
        height: 32px;
        border:none;
    }
</style>
@if (Model == null)
{
    <text>You don't have any attraction list</text>
}
else
{ 
    <table>
    @{int i = 0; }
    @foreach (var item in Model)
    {
        <tr style="height:20px; font-size:medium">
            @{i = i + 1;}
            <td>@i</td>
            <td style="text-align:left">@Html.ActionLink(item.Name, "Show", new { idd = item.ID }, new { @id = item.ID }) </td>
            <td>@Html.ActionLink(" ", "Delete", new { id=item.ID } , new { @class = "imgLinkDelete" })</td>
             <td onclick="showPopup(@item.ID, '@item.Name')" >
                <img src="/Content/images/edit.png" />
            </td>
        </tr>

    }
         <tr>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td><td></td>
            <td>
                 @Html.ActionLink(" ", "Create", null, new { @class = "imgNew" })
            </td>
           
        </tr>
        </table>
}
<div id="popup2">
<div id="content2">
    <form action="#" onsubmit="hidePopup();return false;">
        <input id="popuptext" type="text" />
        <table>
            <tr>
                <td>
                    <input id="popupclose" type="submit" value="" class="imgOk" />

                </td>
                <td>
                    <img src="/Content/images/cancel.png" onclick="cancel()" />
                </td>
            </tr>

        </table>


    </form>
</div>   
    
</div>​