TouristGuide/Models/Place.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TouristGuide.Models
{
    public class Place
    {
        public int ID { get; set; }

        public string imgUrl { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [MinLength(20)]
        [AllowHtml]
        public string Description { get; set; }

        public Coordinates Coordinates { get; set; }

        [Required]
        public Country Country { get; set; }
    }
}

TouristGuide/Controllers/PlaceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TouristGuide.Models;
using TouristGuide.Helpers;
using System.Text.RegularExpressions;
using System.IO;
using System.Data.Entity.Validation;
using System.Diagnostics;
namespace TouristGuide.Controllers
{ 
    public class PlaceController : Controller
    {
        private TouristGuideDB db = new TouristGuideDB();

        //
        // GET: /Place/

        public ViewResult Index(string country, int start = 0, int count = 20)
        {
            List<Place> places = FilterPlaces(country, null, start, count);
            return View(places);
        }

        private List<Place> FilterPlaces(string country, string place, int start, int count)
        {
            IQueryable<Place> places = db.Place.Include(c => c.Country).Include(c => c.Coordinates);

            if (country != null && country != "")
            {
                places = places.Where(a => a.Country != null && a.Country.Name.Contains(country));
            }
            if (place != null && place != "")
            {
                places = places.Where(a => a.Name.Contains(place));
            }

            return places.OrderBy(x => x.Name).Skip(start).Take(count).ToList();
        }

        public ViewResult GetPlaces(string country, string place, int start, int count)
        {
            List<Place> places = FilterPlaces(country, place, start, count);
            return View(places);
        }

        //
        // GET: /Place/Details/5

        public ViewResult Details(int id)
        {
            Place place = db.Place.Include(c => c.Country).Include(c => c.Coordinates).Where(p => p.ID == id).SingleOrDefault();
            return View(place);
        }

        //
        // GET: /Place/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.Countries = DbHelpers.GetCountriesToList();
            return View();
        } 

        //
        // POST: /Place/Create
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(Place place)
        {
            place.Country = db.Country.Find(place.Country.ID);
            db.Place.Add(place);
            db.SaveChanges();
            return RedirectToAction("Index");  
        }
        
        //
        // GET: /Place/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            ViewBag.Countries = DbHelpers.GetCountriesToList();
            Place place = db.Place.Include(c => c.Country).Include(c => c.Coordinates).Where(p => p.ID == id).SingleOrDefault();
            return View(place);
        }

        //
        // POST: /Place/Edit/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(Place place)//, int CountryId)
        {
            //place.Country = db.Country.Find(CountryId);
            ////place.Country.ID = CountryId;
            //if (ModelState.IsValid)
            //{
            //    UpdateModel(place);
            //    //db.Entry(place).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //ViewBag.Countries = DbHelpers.GetCountriesToList();
            //return View(place);
            var updatedPlace = db.Place.Include(c => c.Country).Include(c => c.Coordinates).Where(p => p.ID == place.ID).SingleOrDefault();
            updatedPlace.Coordinates.Latitude = place.Coordinates.Latitude;
            updatedPlace.Coordinates.Longitude = place.Coordinates.Longitude;
            updatedPlace.Country = db.Country.Find(place.Country.ID);
            updatedPlace.Description = place.Description;
            updatedPlace.Name = place.Name;
            db.Entry(updatedPlace).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Place/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            Place place = db.Place.Find(id);
            return View(place);
        }

        //
        // POST: /Place/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Place place = db.Place.Find(id);
            db.Place.Remove(place);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AttractionsForPlace(string place)
        {
            //Get the data from the database
            var attractions = db.Attraction.Where(x => x.Address.City == place || x.Address.Region == place).Include(c => c.Coordinates).Take(100);
            List<PushPinModel> pushpins = new List<PushPinModel>();

            //add info to list of pushpins
            foreach (var attraction in attractions)
            {
                //set the html to pass into the description
                string descriptionHtml;
                if (attraction.Description.Length > 200)
                {
                    descriptionHtml = Regex.Replace(attraction.Description, @"<.*?>", string.Empty);
                    descriptionHtml = descriptionHtml.Substring(0, 200) + "...";
                }
                else
                    descriptionHtml = attraction.Description;

                //add the pushpin info
                pushpins.Add(new PushPinModel
                {
                    Description = descriptionHtml,
                    Latitude = attraction.Coordinates.Latitude,
                    Longitude = attraction.Coordinates.Longitude,
                    Title = "<a href=\"/Attraction/Details/" + attraction.ID + "\">" + attraction.Name + "</a>"
                });
            }

            //return the list as JSON
            return Json(pushpins);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        [Authorize]
        public ActionResult removeImage(int PlaceID)
        {


            string path = AppDomain.CurrentDomain.BaseDirectory;

            Place us = db.Place.Where(x => x.ID == PlaceID).Include("Coordinates").Include("Country").Single();
            System.IO.File.Delete(Path.Combine(path, us.imgUrl));

            us.imgUrl = "";
            db.Entry(us).State = System.Data.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Edit", new { id = us.ID });
        }
        [Authorize]
        [HttpPost]
        public ActionResult ImageCreate(int PlaceID)
        {
            Place us = db.Place.Where(x => x.ID == PlaceID).Include("Coordinates").Include("Country").Single();
            if (us.imgUrl != null && us.imgUrl != "")
            {
                string path = AppDomain.CurrentDomain.BaseDirectory;
                System.IO.File.Delete(Path.Combine(path, us.imgUrl));
            }
            string FileName = "";
            try
            {
                string path = AppDomain.CurrentDomain.BaseDirectory + "Content/PlacesImages/";
                string ext = Request.Files[0].FileName.Substring(Request.Files[0].FileName.LastIndexOf('.'));
                FileName = generateRandomString(32) + ext;
                System.Diagnostics.Debug.WriteLine(FileName);
                Request.Files[0].SaveAs(Path.Combine(path, FileName));
                FileName = Path.Combine("Content/PlacesImages/", FileName);


            }
            catch (NullReferenceException)
            {
                //no photo
            }

            us.imgUrl = FileName;
            db.Entry(us).State = System.Data.EntityState.Modified;
            db.SaveChanges();
  
            return RedirectToAction("Edit", new { id = us.ID });
        }

        public String generateRandomString(int length)
        {
            //Initiate objects & vars    
            Random random = new Random();
            String randomString = "";
            int randNumber;

            //Loop ‘length’ times to generate a random number or character
            for (int i = 0; i < length; i++)
            {
                if (random.Next(1, 3) == 1)
                    randNumber = random.Next(97, 123); //char {a-z}
                else
                    randNumber = random.Next(48, 58); //int {0-9}

                //append random char or digit to random string
                randomString = randomString + (char)randNumber;
            }
            //return the random string
            return randomString;
        }
    }
}

TouristGuide/Views/Place/Create.cshtml
@model TouristGuide.Models.Place

@{
    ViewBag.Title = "Create city/region";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/tiny_mce/tiny_mce.js")" type="text/javascript"></script>
<script type="text/javascript">
    tinyMCE.init({
        mode: "specific_textareas",
        editor_selector: "TinyMCE",
        theme: "advanced"
    });

    function UpdateText() {
        var text = tinyMCE.get('Description').getContent();
        $('#Description').html(text);
    }
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Details</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { @class = "TinyMCE" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </fieldset>
    
    <fieldset>
        <legend>Location</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Coordinates.Latitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coordinates.Latitude)
            @Html.ValidationMessageFor(model => model.Coordinates.Latitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Coordinates.Longitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coordinates.Longitude)
            @Html.ValidationMessageFor(model => model.Coordinates.Longitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Country)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Country.ID, new SelectList(ViewBag.Countries, "Value", "Text"))
        </div>

        <p>
            <input type="submit" value="Create" onclick="UpdateText()" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TouristGuide/Views/Place/Delete.cshtml
@model TouristGuide.Models.Place

@{
    ViewBag.Title = Model.Name;
}

<h3>Are you sure you want to delete this place?</h3>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

<br />

<h4>Description:</h4>

<p>@Html.Raw(Model.Description)</p>

TouristGuide/Views/Place/Details.cshtml
@model TouristGuide.Models.Place
@{
    ViewBag.Title = Model.Name;
}
<script type="text/javascript" src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=6.2"></script>
<script type="text/javascript">
    $(document).ready(function () {
        GetMap();
        //call the action created to retrieve the data
        $.post("/Place/AttractionsForPlace?place=@Model.Name", null, function (data) {
            //iterate through the 'data' retireved
            $.each(data, function (item, location) {
                AddLocationPin(location.Latitude, location.Longitude, location.Title, location.Description);
            });
        });
    });
    var map = null;
    function GetMap() {
        map = new VEMap('myMap');
        map.LoadMap(new VELatLong(@Model.Coordinates.Latitude, @Model.Coordinates.Longitude), 11, 'Road', false);
    }
    function AddLocationPin(latitude, longitude, title, description) {      
        //create new pushpin shape      
        shape = new VEShape(VEShapeType.Pushpin, new VELatLong(latitude, longitude));      
        //set title for info box      
        shape.SetTitle(title);      
        //set html for info box      
        shape.SetDescription(description);      
        //add pin      
        map.AddShape(shape);  
    }

</script>
Country: @Html.ActionLink(Model.Country.Name, "Details", "Country", new { id = Model.Country.ID }, null)<br />
@Html.ActionLink("Show Attractions", "Index", "Attraction", new { place = Model.Name }, null)
@if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}
<div id='myMap' style="position: relative; width: 600px; height: 400px">
</div>
<p>@Html.Raw(Model.Description)</p>

TouristGuide/Views/Place/Edit.cshtml
@model TouristGuide.Models.Place

@{
    ViewBag.Title = Model.Name + " - Edit";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/tiny_mce/tiny_mce.js")" type="text/javascript"></script>
<script type="text/javascript">
    tinyMCE.init({
        mode: "specific_textareas",
        editor_selector: "TinyMCE",
        theme: "advanced"
    });

    function UpdateText() {
        var text = tinyMCE.get('Description').getContent();
        $('#Description').html(text);
    }
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Details</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { @class = "TinyMCE" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </fieldset>
    
    <fieldset>
        <legend>Location</legend>

        @Html.HiddenFor(model => model.Coordinates.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Coordinates.Latitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coordinates.Latitude)
            @Html.ValidationMessageFor(model => model.Coordinates.Latitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Coordinates.Longitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Coordinates.Longitude)
            @Html.ValidationMessageFor(model => model.Coordinates.Longitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Country)
        </div>
        <div class="editor-field">
            @*@Html.HiddenFor(model => model.Country.ID)
            @Html.HiddenFor(model => model.Country.Name)
            @Html.HiddenFor(model => model.Country.Description)
            @Html.EditorFor(x => x.Country)*@
            @Html.DropDownListFor(model => model.Country.ID, new SelectList(ViewBag.Countries, "Value", "Text", Model.Country.ID))
        </div>
    </fieldset>

        <p>
            <input type="submit" value="Save" onclick="UpdateText()" />
        </p>
}
@if (Model.imgUrl != null && Model.imgUrl!="")
{
	<h3 style="display: inline-block; margin-right:20px;">Images</h3>
    	
	<div class="post-images">
		<ul class="thumbs noscript">
	
				<li>
					<a class="thumb" href="@Url.Content("~/" + Model.imgUrl)" title="Image 1">
						<img src="@Url.Content("~/" + Model.imgUrl)" alt="Image 1" />
					</a>
				</li>
   
		</ul>
        @Html.ActionLink("Delete", "removeImage", new { PlaceID = Model.ID })
	</div>
}

<div id="addImageDiv">
		@using (Html.BeginForm("ImageCreate", "Place", FormMethod.Post, new { enctype = "multipart/form-data", id =  "addImage",
                                onsubmit = "AddImage()"}))
  {
			@Html.ValidationSummary(true)
			<fieldset>
				<legend>Add Image</legend>
                @Html.Hidden("PlaceID", Model.ID)  
				    <div class="editor-field-images">
                        <input type="file" name="FileName" id="FileName"/>
                    </div>
                    
                    <br />
                <input type="submit" value="Send!" />
			</fieldset>
  }
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TouristGuide/Views/Place/GetPlaces.cshtml
@model IEnumerable<TouristGuide.Models.Place>
           
@{
    Layout = null;
}

@Html.DisplayFor(x=>x)

TouristGuide/Views/Place/Index.cshtml
@model IEnumerable<TouristGuide.Models.Place>

@{
    ViewBag.Title = "Cities and regions";
}

<link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript">
    //pagger scrolling and filtering
    var more = true;
    var loading = false;
    var count = 20;
    var start = 0;
    var loaderImg = null;
    var country = '';
    var place = '';

    $(document).ready(function () {
        $("#country").val('@Request.QueryString["country"]');
        country = $("#country").val();
        place = $("#place").val();

        if ($('.regionBar').length < count) {
            more = false;
            HideLoading();
        }
        else {
            ShowLoading();
            $(window).scroll($.proxy(ScrollHandler, this));
        }

        AddActions();
      });

    function AddActions() {
        $(".regionBar").click(function () {
            var id = $(this).attr("name");
            var url = "/place/details/";
            window.location.replace(url + id);
        });
        $(".regionBar").hover(
          function () {
              $(this).css("background-image", "url(/Content/images/countryGreenDark.png)");
              $(this).css("cursor", "pointer");
          },
          function () {
              $(this).css("background-image", "url(/Content/images/countryGreen.png)");
              $(this).css("cursor", "auto");
          });
      }

    function ShowLoading() {
        loaderImg = $("<div>").addClass("bar").css("clear", "both").css("text-align", "center");
        var img = $("<img>").attr("src", "/Content/images/indicator.gif");
        loaderImg.append(img);
        $(".table_center").append(loaderImg);
    }

    function HideLoading() {
        $(loaderImg).remove();
    }

    function isScrolledIntoView(elem) {
        var docViewTop = $(window).scrollTop();
        var docViewBottom = docViewTop + $(window).height();

        var elemTop = $(elem).offset().top;
        var elemBottom = elemTop + $(elem).height();

        return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
    }

    function ScrollHandler(event) {
        if (isScrolledIntoView(loaderImg) && loading == false) {
            GetPage();
        }
    }

    function GetPage(event) {
        if (more == true) {
            start += count;
            GetElements();
            loading = true;
        }
    }

    function GetElements() {
        $.ajax({
            url: '@Url.Action("GetPlaces", "Place")',
            type: 'GET',
            contentType: 'application/json',
            data: { country: country, place: place,
                    start: start, count: count
            },
            dataType: 'html',
            success: $.proxy(Results, this)
        });
    }

    function Results(data) {
        if (data != null && data.trim() != '') {
            HideLoading();
            $(".table_center").append(data);
            if (data.split('<div class="regionBar"').length - 1 < count) {
                more = false;
                HideLoading();
            }
            else {
                ShowLoading();
                loading = false;
            }
            AddActions();
        }
        else {
            more = false;
            HideLoading();
            $("#noResults").attr("style", "");
        }
    }

    function Filter() {
        country = $("#country").val();
        place = $("#place").val();
        $("#noResults").attr("style", "display:none;");

        $(".regionBar").remove();
        ShowLoading();

        more = true;
        loading = true;
        start = 0;
        GetElements();
    }

</script>
@Html.Partial("Partial/Autocomplete")

@if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<div class="center border-bottom">
<form action="/Place/Index" method="get">
<div style="font-size:20px;margin-bottom:20px;">Filter City/Region</div>
      <span style="font-size:16px;padding-right:5px;">country:</span><input type="text" name="country" id="country" />
     <span style="font-size:16px;padding-right:5px;margin-left:20px;">city/region:</span> <input type="text" name="place" id ="place" />
    <input type="submit" value="Filter" onclick="Filter(); return false;" style="margin-left:20px;color:Gray;"/>
</form>
</div>

<div class="table_center">     
       <span style="font-size:20px;">Cities / Regions</span>
        @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("admin"))
        {
           <div>
           admin
           </div>
        }
  
  <div style="margin-top:20px;">  
    <div id="noResults" class="regionResults"
    @if (Model == null || (Model != null && Model.Count() == 0))
    {
        @:>
    }
    else
    { 
        @: style="display:none;">
    }
        <span style="color: White; font-size: 20px;">No results found.</span>
    </div>

    @Html.DisplayFor(x=>x)
  </div>
</div>